### ISSUE TITLE
Ideas/TODO

### ISSUE THREAD

**Issue by ghost** [Team4028/2023-Drive#1]
- [ ] Pose estimation & vision measurement resets?

- [ ] Figure out actual usage in a project (vendordep, template)
- [ ] Get public docs set up
- [ ] ADD TO BEAKLIB!
- [ ] I zone setting
- [ ] Swerve testing:
  * [x] First, test regular BeakSwerveDrivetrain.
  * [x] Then, test BeakEpicSwerveDrivetrain.
  * [x] Finally, set up distance-per-pulse in BeakEpicSwerveDrivetrain
  * [ ] Once everything is tested and working, move BeakEpicSwerveDrivetrain and related to BeakSwerveDrivetrain.

**Comment by ghost** [comment]
swerve drive needs velocity PID(?) and accurate odometry

**Comment by ghost** [comment]
Distance per pulse in EpicSwerve is off by 0.47
